// MCP Directory — curated server data
// tier: free = works at $0 | freemium = free tier, real usage costs | paid = paid product/API required
// badge: official (vendor-built) | community | reference (Anthropic reference server)
// tr: stdio | http | sse   inst.t: npx | uvx | docker | http | sse | docs
const CATS = {
  dev:     { label: "Dev Tools",            icon: "🛠️" },
  browser: { label: "Browser & Automation", icon: "🌐" },
  db:      { label: "Databases",            icon: "🗄️" },
  cloud:   { label: "Cloud & Infra",        icon: "☁️" },
  search:  { label: "Search & Scraping",    icon: "🔍" },
  prod:    { label: "Productivity",         icon: "📋" },
  comm:    { label: "Communication",        icon: "💬" },
  fin:     { label: "Finance & Payments",   icon: "💳" },
  ai:      { label: "AI & ML",              icon: "🤖" },
  secmon:  { label: "Security & Monitoring",icon: "🛡️" },
  design:  { label: "Design & 3D",          icon: "🎨" },
  know:    { label: "Knowledge & Content",  icon: "📚" },
  biz:     { label: "Business & CRM",       icon: "🏢" },
  util:    { label: "Utilities",            icon: "🧰" }
};

const SERVERS = [
  // ---------- Reference servers (Anthropic) ----------
  { id:"filesystem", n:"Filesystem", cat:"util", tier:"free", badge:"reference", tr:"stdio",
    repo:"modelcontextprotocol/servers", url:"https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    use:"Read, write, search and edit local files and directories from your agent.",
    env:[], inst:{t:"npx", v:"@modelcontextprotocol/server-filesystem", args:["/path/to/allowed/dir"]},
    sec:"Grants disk access — always scope to specific directories, never your whole drive." },
  { id:"fetch", n:"Fetch", cat:"util", tier:"free", badge:"reference", tr:"stdio",
    repo:"modelcontextprotocol/servers", url:"https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    use:"Fetch any URL and convert web pages to markdown for the model to read.",
    env:[], inst:{t:"uvx", v:"mcp-server-fetch"},
    sec:"Fetched pages can contain prompt injection — treat web content as untrusted input." },
  { id:"git", n:"Git", cat:"dev", tier:"free", badge:"reference", tr:"stdio",
    repo:"modelcontextprotocol/servers", url:"https://github.com/modelcontextprotocol/servers/tree/main/src/git",
    use:"Read, search and analyze local git repositories — log, diff, blame, status.",
    env:[], inst:{t:"uvx", v:"mcp-server-git"} },
  { id:"memory", n:"Memory (Knowledge Graph)", cat:"ai", tier:"free", badge:"reference", tr:"stdio",
    repo:"modelcontextprotocol/servers", url:"https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    use:"Persistent knowledge-graph memory — the agent remembers entities and relations across chats.",
    env:[], inst:{t:"npx", v:"@modelcontextprotocol/server-memory"} },
  { id:"seqthink", n:"Sequential Thinking", cat:"ai", tier:"free", badge:"reference", tr:"stdio",
    repo:"modelcontextprotocol/servers", url:"https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    use:"Structured step-by-step reasoning tool — break complex problems into revisable thought chains.",
    env:[], inst:{t:"npx", v:"@modelcontextprotocol/server-sequential-thinking"} },
  { id:"time", n:"Time", cat:"util", tier:"free", badge:"reference", tr:"stdio",
    repo:"modelcontextprotocol/servers", url:"https://github.com/modelcontextprotocol/servers/tree/main/src/time",
    use:"Current time and timezone conversions — reliable dates for scheduling and logs.",
    env:[], inst:{t:"uvx", v:"mcp-server-time"} },

  // ---------- Dev Tools ----------
  { id:"github", n:"GitHub", cat:"dev", tier:"free", badge:"official", tr:"http",
    repo:"github/github-mcp-server", url:"https://github.com/github/github-mcp-server",
    use:"Manage repos, issues, PRs, Actions runs, code scanning — full GitHub from your agent.",
    env:["GITHUB_PAT"], inst:{t:"http", v:"https://api.githubcopilot.com/mcp/"},
    sec:"Use a fine-grained PAT scoped to only the repos the agent needs." },
  { id:"gitlab", n:"GitLab", cat:"dev", tier:"freemium", badge:"community", tr:"stdio",
    repo:"zereight/gitlab-mcp", url:"https://github.com/zereight/gitlab-mcp",
    use:"Projects, merge requests, issues and pipelines on GitLab (cloud or self-hosted).",
    env:["GITLAB_PERSONAL_ACCESS_TOKEN"], inst:{t:"npx", v:"@zereight/mcp-gitlab"} },
  { id:"context7", n:"Context7", cat:"dev", tier:"free", badge:"official", tr:"http",
    repo:"upstash/context7", url:"https://github.com/upstash/context7",
    use:"Up-to-date, version-specific library docs injected into prompts — kills hallucinated APIs.",
    env:[], inst:{t:"http", v:"https://mcp.context7.com/mcp"} },
  { id:"deepwiki", n:"DeepWiki", cat:"dev", tier:"free", badge:"official", tr:"http",
    repo:null, url:"https://docs.devin.ai/work-with-devin/deepwiki-mcp",
    use:"Ask questions about any public GitHub repo — AI-generated wiki answers from Cognition.",
    env:[], inst:{t:"http", v:"https://mcp.deepwiki.com/mcp"} },
  { id:"semgrep", n:"Semgrep", cat:"dev", tier:"free", badge:"official", tr:"stdio",
    repo:"semgrep/mcp", url:"https://github.com/semgrep/mcp",
    use:"Static-analysis security scans on code the agent writes — catch vulns before commit.",
    env:[], inst:{t:"uvx", v:"semgrep-mcp"} },
  { id:"circleci", n:"CircleCI", cat:"dev", tier:"freemium", badge:"official", tr:"stdio",
    repo:"CircleCI-Public/mcp-server-circleci", url:"https://github.com/CircleCI-Public/mcp-server-circleci",
    use:"Find and fix failed CI builds — the agent reads pipeline logs and flaky tests.",
    env:["CIRCLECI_TOKEN"], inst:{t:"npx", v:"@circleci/mcp-server-circleci"} },
  { id:"postman", n:"Postman", cat:"dev", tier:"freemium", badge:"official", tr:"stdio",
    repo:"postmanlabs/postman-mcp-server", url:"https://github.com/postmanlabs/postman-mcp-server",
    use:"Manage Postman collections, environments and run API requests from your agent.",
    env:["POSTMAN_API_KEY"], inst:{t:"docs", v:"https://github.com/postmanlabs/postman-mcp-server"} },
  { id:"prisma", n:"Prisma", cat:"dev", tier:"free", badge:"official", tr:"stdio",
    repo:"prisma/prisma", url:"https://www.prisma.io/docs/postgres/mcp-server",
    use:"Manage Prisma schema, migrations and Prisma Postgres databases via natural language.",
    env:[], inst:{t:"npx", v:"prisma", args:["mcp"]} },
  { id:"shadcn", n:"shadcn/ui", cat:"dev", tier:"free", badge:"official", tr:"stdio",
    repo:"shadcn-ui/ui", url:"https://ui.shadcn.com/docs/mcp",
    use:"Browse and install shadcn registry components into your project from the agent.",
    env:[], inst:{t:"npx", v:"shadcn@latest", args:["mcp", "init"]} },
  { id:"n8n", n:"n8n (community)", cat:"dev", tier:"free", badge:"community", tr:"stdio",
    repo:"czlonkowski/n8n-mcp", url:"https://github.com/czlonkowski/n8n-mcp",
    use:"Build n8n workflows with full node documentation — the agent knows every n8n node.",
    env:[], inst:{t:"npx", v:"n8n-mcp"} },

  // ---------- Browser & Automation ----------
  { id:"playwright", n:"Playwright", cat:"browser", tier:"free", badge:"official", tr:"stdio",
    repo:"microsoft/playwright-mcp", url:"https://github.com/microsoft/playwright-mcp",
    use:"Drive a real browser via accessibility tree — click, type, screenshot, test web apps.",
    env:[], inst:{t:"npx", v:"@playwright/mcp@latest"} },
  { id:"chromedevtools", n:"Chrome DevTools", cat:"browser", tier:"free", badge:"official", tr:"stdio",
    repo:"ChromeDevTools/chrome-devtools-mcp", url:"https://github.com/ChromeDevTools/chrome-devtools-mcp",
    use:"Debug live Chrome — inspect network, console, performance traces and DOM from the agent.",
    env:[], inst:{t:"npx", v:"chrome-devtools-mcp@latest"} },
  { id:"browsermcp", n:"Browser MCP", cat:"browser", tier:"free", badge:"community", tr:"stdio",
    repo:"BrowserMCP/mcp", url:"https://browsermcp.io",
    use:"Automate YOUR logged-in Chrome via extension — uses your sessions, no re-login.",
    env:[], inst:{t:"npx", v:"@browsermcp/mcp@latest"},
    sec:"Runs with your live browser sessions — the agent can act as you on any open site." },
  { id:"browserbase", n:"Browserbase", cat:"browser", tier:"freemium", badge:"official", tr:"stdio",
    repo:"browserbase/mcp-server-browserbase", url:"https://github.com/browserbase/mcp-server-browserbase",
    use:"Cloud headless browsers with Stagehand AI actions — scale scraping/automation off your machine.",
    env:["BROWSERBASE_API_KEY","BROWSERBASE_PROJECT_ID"], inst:{t:"npx", v:"@browserbasehq/mcp"} },
  { id:"puppeteer", n:"Puppeteer (archived)", cat:"browser", tier:"free", badge:"reference", tr:"stdio",
    repo:"modelcontextprotocol/servers-archived", url:"https://github.com/modelcontextprotocol/servers-archived/tree/main/src/puppeteer",
    use:"Legacy reference browser automation — archived; prefer Playwright MCP.",
    env:[], inst:{t:"npx", v:"@modelcontextprotocol/server-puppeteer"} },

  // ---------- Databases ----------
  { id:"postgres", n:"Postgres MCP Pro", cat:"db", tier:"free", badge:"community", tr:"stdio",
    repo:"crystaldba/postgres-mcp", url:"https://github.com/crystaldba/postgres-mcp",
    use:"Query PostgreSQL plus health checks, index tuning and EXPLAIN analysis.",
    env:["DATABASE_URI"], inst:{t:"uvx", v:"postgres-mcp"},
    sec:"Supports restricted read-only mode — use it for production databases." },
  { id:"mysql", n:"MySQL", cat:"db", tier:"free", badge:"community", tr:"stdio",
    repo:"benborla/mcp-server-mysql", url:"https://github.com/benborla/mcp-server-mysql",
    use:"Query MySQL databases with configurable read-only or write access.",
    env:["MYSQL_HOST","MYSQL_USER","MYSQL_PASS","MYSQL_DB"], inst:{t:"npx", v:"@benborla29/mcp-server-mysql"} },
  { id:"sqlite", n:"SQLite (archived)", cat:"db", tier:"free", badge:"reference", tr:"stdio",
    repo:"modelcontextprotocol/servers-archived", url:"https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite",
    use:"Query local SQLite files — simple, zero-setup local data analysis.",
    env:[], inst:{t:"uvx", v:"mcp-server-sqlite", args:["--db-path","./data.db"]} },
  { id:"mongodb", n:"MongoDB", cat:"db", tier:"free", badge:"official", tr:"stdio",
    repo:"mongodb-js/mongodb-mcp-server", url:"https://github.com/mongodb-js/mongodb-mcp-server",
    use:"Query and manage MongoDB + Atlas clusters — find, aggregate, index, admin.",
    env:["MDB_MCP_CONNECTION_STRING"], inst:{t:"npx", v:"mongodb-mcp-server"} },
  { id:"redis", n:"Redis", cat:"db", tier:"free", badge:"official", tr:"stdio",
    repo:"redis/mcp-redis", url:"https://github.com/redis/mcp-redis",
    use:"Natural-language access to Redis — keys, hashes, streams, vector search.",
    env:["REDIS_URL"], inst:{t:"docs", v:"https://github.com/redis/mcp-redis"} },
  { id:"motherduck", n:"MotherDuck / DuckDB", cat:"db", tier:"freemium", badge:"official", tr:"stdio",
    repo:"motherduckdb/mcp-server-motherduck", url:"https://github.com/motherduckdb/mcp-server-motherduck",
    use:"SQL analytics on local DuckDB files or MotherDuck cloud — fast columnar queries.",
    env:["MOTHERDUCK_TOKEN"], inst:{t:"uvx", v:"mcp-server-motherduck"} },
  { id:"clickhouse", n:"ClickHouse", cat:"db", tier:"freemium", badge:"official", tr:"stdio",
    repo:"ClickHouse/mcp-clickhouse", url:"https://github.com/ClickHouse/mcp-clickhouse",
    use:"Run analytical SQL on ClickHouse clusters and query the public playground.",
    env:["CLICKHOUSE_HOST","CLICKHOUSE_USER","CLICKHOUSE_PASSWORD"], inst:{t:"uvx", v:"mcp-clickhouse"} },
  { id:"elasticsearch", n:"Elasticsearch", cat:"db", tier:"freemium", badge:"official", tr:"stdio",
    repo:"elastic/mcp-server-elasticsearch", url:"https://github.com/elastic/mcp-server-elasticsearch",
    use:"Search and inspect Elasticsearch indices with natural language queries.",
    env:["ES_URL","ES_API_KEY"], inst:{t:"npx", v:"@elastic/mcp-server-elasticsearch"} },
  { id:"neo4j", n:"Neo4j", cat:"db", tier:"freemium", badge:"official", tr:"stdio",
    repo:"neo4j-contrib/mcp-neo4j", url:"https://github.com/neo4j-contrib/mcp-neo4j",
    use:"Cypher queries and graph modeling on Neo4j — plus a graph-based agent memory.",
    env:["NEO4J_URI","NEO4J_USERNAME","NEO4J_PASSWORD"], inst:{t:"uvx", v:"mcp-neo4j-cypher"} },
  { id:"neon", n:"Neon", cat:"db", tier:"freemium", badge:"official", tr:"stdio",
    repo:"neondatabase/mcp-server-neon", url:"https://github.com/neondatabase/mcp-server-neon",
    use:"Serverless Postgres — create branches, run SQL, manage projects conversationally.",
    env:["NEON_API_KEY"], inst:{t:"npx", v:"@neondatabase/mcp-server-neon", args:["start"]} },
  { id:"chroma", n:"Chroma", cat:"db", tier:"free", badge:"official", tr:"stdio",
    repo:"chroma-core/chroma-mcp", url:"https://github.com/chroma-core/chroma-mcp",
    use:"Vector database for RAG — collections, embeddings, semantic search, local or cloud.",
    env:[], inst:{t:"uvx", v:"chroma-mcp"} },
  { id:"qdrant", n:"Qdrant", cat:"db", tier:"free", badge:"official", tr:"stdio",
    repo:"qdrant/mcp-server-qdrant", url:"https://github.com/qdrant/mcp-server-qdrant",
    use:"Semantic memory on Qdrant vector DB — store and retrieve by meaning.",
    env:["QDRANT_URL","COLLECTION_NAME"], inst:{t:"uvx", v:"mcp-server-qdrant"} },
  { id:"pinecone", n:"Pinecone", cat:"db", tier:"freemium", badge:"official", tr:"stdio",
    repo:"pinecone-io/pinecone-mcp", url:"https://github.com/pinecone-io/pinecone-mcp",
    use:"Manage Pinecone indexes, upsert docs and semantic search from the agent.",
    env:["PINECONE_API_KEY"], inst:{t:"npx", v:"@pinecone-database/mcp"} },
  { id:"milvus", n:"Milvus", cat:"db", tier:"free", badge:"official", tr:"stdio",
    repo:"zilliztech/mcp-server-milvus", url:"https://github.com/zilliztech/mcp-server-milvus",
    use:"Vector search and collection management on Milvus / Zilliz Cloud.",
    env:["MILVUS_URI"], inst:{t:"docs", v:"https://github.com/zilliztech/mcp-server-milvus"} },
  { id:"dbt", n:"dbt", cat:"db", tier:"freemium", badge:"official", tr:"stdio",
    repo:"dbt-labs/dbt-mcp", url:"https://github.com/dbt-labs/dbt-mcp",
    use:"Run dbt models, inspect lineage and query the semantic layer.",
    env:[], inst:{t:"uvx", v:"dbt-mcp"} },
  { id:"snowflake", n:"Snowflake", cat:"db", tier:"paid", badge:"official", tr:"stdio",
    repo:"Snowflake-Labs/mcp", url:"https://github.com/Snowflake-Labs/mcp",
    use:"Cortex Search, Cortex Analyst and SQL on your Snowflake account.",
    env:[], inst:{t:"docs", v:"https://github.com/Snowflake-Labs/mcp"} },

  // ---------- Cloud & Infra ----------
  { id:"aws", n:"AWS (awslabs suite)", cat:"cloud", tier:"freemium", badge:"official", tr:"stdio",
    repo:"awslabs/mcp", url:"https://github.com/awslabs/mcp",
    use:"20+ official servers: CDK, cost analysis, Bedrock KB, docs, Lambda, EKS and more.",
    env:["AWS_PROFILE"], inst:{t:"uvx", v:"awslabs.core-mcp-server@latest"},
    sec:"Uses your AWS credentials — scope IAM narrowly; cost-analysis server is read-only." },
  { id:"azure", n:"Azure", cat:"cloud", tier:"freemium", badge:"official", tr:"stdio",
    repo:"Azure/azure-mcp", url:"https://github.com/Azure/azure-mcp",
    use:"Query and manage Azure resources — storage, Cosmos, AKS, monitor logs.",
    env:[], inst:{t:"npx", v:"@azure/mcp@latest", args:["server","start"]} },
  { id:"cloudflare", n:"Cloudflare", cat:"cloud", tier:"freemium", badge:"official", tr:"sse",
    repo:"cloudflare/mcp-server-cloudflare", url:"https://github.com/cloudflare/mcp-server-cloudflare",
    use:"13 hosted servers: Workers bindings, observability, Radar, docs, browser rendering.",
    env:[], inst:{t:"sse", v:"https://docs.mcp.cloudflare.com/sse"} },
  { id:"vercel", n:"Vercel", cat:"cloud", tier:"freemium", badge:"official", tr:"http",
    repo:null, url:"https://vercel.com/docs/mcp/vercel-mcp",
    use:"Manage deployments, projects, logs and docs on Vercel from your agent.",
    env:[], inst:{t:"http", v:"https://mcp.vercel.com"} },
  { id:"netlify", n:"Netlify", cat:"cloud", tier:"freemium", badge:"official", tr:"stdio",
    repo:"netlify/netlify-mcp", url:"https://github.com/netlify/netlify-mcp",
    use:"Create, deploy and manage Netlify sites — deploy straight from the conversation.",
    env:[], inst:{t:"npx", v:"@netlify/mcp"} },
  { id:"heroku", n:"Heroku", cat:"cloud", tier:"paid", badge:"official", tr:"stdio",
    repo:"heroku/heroku-mcp-server", url:"https://github.com/heroku/heroku-mcp-server",
    use:"Manage Heroku apps, dynos, add-ons and logs (no free tier since 2022).",
    env:["HEROKU_API_KEY"], inst:{t:"npx", v:"@heroku/mcp-server"} },
  { id:"render", n:"Render", cat:"cloud", tier:"freemium", badge:"official", tr:"http",
    repo:"render-oss/render-mcp-server", url:"https://render.com/docs/mcp-server",
    use:"Manage Render services, deploys, env vars and Postgres from the agent.",
    env:["RENDER_API_KEY"], inst:{t:"http", v:"https://mcp.render.com/mcp"} },
  { id:"supabase", n:"Supabase", cat:"cloud", tier:"freemium", badge:"official", tr:"stdio",
    repo:"supabase/mcp", url:"https://github.com/supabase/mcp",
    use:"Manage projects, run SQL, apply migrations, generate types on Supabase.",
    env:["SUPABASE_ACCESS_TOKEN"], inst:{t:"npx", v:"@supabase/mcp-server-supabase@latest", args:["--read-only"]},
    sec:"Default to --read-only and a project-scoped token; write mode can alter prod schema." },
  { id:"firebase", n:"Firebase", cat:"cloud", tier:"freemium", badge:"official", tr:"stdio",
    repo:"firebase/firebase-tools", url:"https://firebase.google.com/docs/cli/mcp-server",
    use:"Firestore, Auth users, Storage rules and project config via Firebase CLI.",
    env:[], inst:{t:"npx", v:"firebase-tools@latest", args:["experimental:mcp"]} },
  { id:"upstash", n:"Upstash", cat:"cloud", tier:"freemium", badge:"official", tr:"stdio",
    repo:"upstash/mcp-server", url:"https://github.com/upstash/mcp-server",
    use:"Manage serverless Redis/QStash — create databases, run commands, check usage.",
    env:[], inst:{t:"docs", v:"https://github.com/upstash/mcp-server"} },
  { id:"docker", n:"Docker Hub", cat:"cloud", tier:"free", badge:"official", tr:"stdio",
    repo:"docker/hub-mcp", url:"https://github.com/docker/hub-mcp",
    use:"Search images, inspect tags and manage Docker Hub repositories.",
    env:[], inst:{t:"docs", v:"https://github.com/docker/hub-mcp"} },
  { id:"kubernetes", n:"Kubernetes", cat:"cloud", tier:"free", badge:"community", tr:"stdio",
    repo:"containers/kubernetes-mcp-server", url:"https://github.com/containers/kubernetes-mcp-server",
    use:"kubectl-grade cluster ops — pods, deployments, logs, events, helm.",
    env:[], inst:{t:"npx", v:"kubernetes-mcp-server@latest"},
    sec:"Uses your kubeconfig — point it at a non-prod context unless you mean it." },
  { id:"terraform", n:"Terraform", cat:"cloud", tier:"free", badge:"official", tr:"stdio",
    repo:"hashicorp/terraform-mcp-server", url:"https://github.com/hashicorp/terraform-mcp-server",
    use:"Registry-aware IaC authoring — accurate provider/module docs while writing HCL.",
    env:[], inst:{t:"docker", v:"hashicorp/terraform-mcp-server"} },

  // ---------- Search & Scraping ----------
  { id:"brave", n:"Brave Search", cat:"search", tier:"freemium", badge:"official", tr:"stdio",
    repo:"brave/brave-search-mcp-server", url:"https://github.com/brave/brave-search-mcp-server",
    use:"Web, news, image and video search with a generous free API tier.",
    env:["BRAVE_API_KEY"], inst:{t:"npx", v:"@brave/brave-search-mcp-server"} },
  { id:"exa", n:"Exa", cat:"search", tier:"freemium", badge:"official", tr:"http",
    repo:"exa-labs/exa-mcp-server", url:"https://github.com/exa-labs/exa-mcp-server",
    use:"AI-native web search + company research, LinkedIn search and crawling.",
    env:["EXA_API_KEY"], inst:{t:"http", v:"https://mcp.exa.ai/mcp"} },
  { id:"tavily", n:"Tavily", cat:"search", tier:"freemium", badge:"official", tr:"stdio",
    repo:"tavily-ai/tavily-mcp", url:"https://github.com/tavily-ai/tavily-mcp",
    use:"Search, extract, map and crawl built for RAG pipelines — 1k free calls/month.",
    env:["TAVILY_API_KEY"], inst:{t:"npx", v:"tavily-mcp@latest"} },
  { id:"perplexity", n:"Perplexity", cat:"search", tier:"paid", badge:"official", tr:"stdio",
    repo:"perplexityai/modelcontextprotocol", url:"https://github.com/perplexityai/modelcontextprotocol",
    use:"Sonar API — real-time researched answers with citations inside your agent.",
    env:["PERPLEXITY_API_KEY"], inst:{t:"npx", v:"server-perplexity-ask"} },
  { id:"kagi", n:"Kagi Search", cat:"search", tier:"paid", badge:"official", tr:"stdio",
    repo:"kagisearch/kagimcp", url:"https://github.com/kagisearch/kagimcp",
    use:"Ad-free premium search and page summarizer via Kagi API.",
    env:["KAGI_API_KEY"], inst:{t:"uvx", v:"kagimcp"} },
  { id:"duckduckgo", n:"DuckDuckGo", cat:"search", tier:"free", badge:"community", tr:"stdio",
    repo:"nickclyde/duckduckgo-mcp-server", url:"https://github.com/nickclyde/duckduckgo-mcp-server",
    use:"Free web search with no API key — rate-limited but zero-setup.",
    env:[], inst:{t:"uvx", v:"duckduckgo-mcp-server"} },
  { id:"firecrawl", n:"Firecrawl", cat:"search", tier:"freemium", badge:"official", tr:"stdio",
    repo:"firecrawl/firecrawl-mcp-server", url:"https://github.com/firecrawl/firecrawl-mcp-server",
    use:"Scrape/crawl any site to clean markdown — handles JS rendering and PDFs.",
    env:["FIRECRAWL_API_KEY"], inst:{t:"npx", v:"firecrawl-mcp"} },
  { id:"apify", n:"Apify", cat:"search", tier:"freemium", badge:"official", tr:"http",
    repo:"apify/apify-mcp-server", url:"https://github.com/apify/apify-mcp-server",
    use:"Run 6,000+ scrapers (Actors): social media, maps, e-commerce, TikTok, Insta.",
    env:["APIFY_TOKEN"], inst:{t:"http", v:"https://mcp.apify.com"} },
  { id:"brightdata", n:"Bright Data", cat:"search", tier:"freemium", badge:"official", tr:"stdio",
    repo:"brightdata/brightdata-mcp", url:"https://github.com/brightdata/brightdata-mcp",
    use:"Unblockable scraping at scale — proxy network + search + structured extractors.",
    env:["API_TOKEN"], inst:{t:"npx", v:"@brightdata/mcp"} },
  { id:"oxylabs", n:"Oxylabs", cat:"search", tier:"paid", badge:"official", tr:"stdio",
    repo:"oxylabs/oxylabs-mcp", url:"https://github.com/oxylabs/oxylabs-mcp",
    use:"Enterprise web scraping API — Google/Amazon parsing behind proxies.",
    env:["OXYLABS_USERNAME","OXYLABS_PASSWORD"], inst:{t:"uvx", v:"oxylabs-mcp"} },

  // ---------- Productivity ----------
  { id:"notion", n:"Notion", cat:"prod", tier:"freemium", badge:"official", tr:"http",
    repo:"makenotion/notion-mcp-server", url:"https://github.com/makenotion/notion-mcp-server",
    use:"Search, read and write Notion pages and databases from your agent.",
    env:[], inst:{t:"http", v:"https://mcp.notion.com/mcp"} },
  { id:"linear", n:"Linear", cat:"prod", tier:"freemium", badge:"official", tr:"sse",
    repo:null, url:"https://linear.app/docs/mcp",
    use:"Create and update Linear issues, projects and cycles conversationally.",
    env:[], inst:{t:"sse", v:"https://mcp.linear.app/sse"} },
  { id:"atlassian", n:"Atlassian (Jira + Confluence)", cat:"prod", tier:"freemium", badge:"official", tr:"sse",
    repo:null, url:"https://www.atlassian.com/platform/remote-mcp-server",
    use:"Jira issues and Confluence pages — search, create, update with OAuth.",
    env:[], inst:{t:"sse", v:"https://mcp.atlassian.com/v1/sse"} },
  { id:"asana", n:"Asana", cat:"prod", tier:"freemium", badge:"official", tr:"sse",
    repo:null, url:"https://developers.asana.com/docs/mcp-server",
    use:"Tasks, projects and goals in Asana via hosted OAuth server.",
    env:[], inst:{t:"sse", v:"https://mcp.asana.com/sse"} },
  { id:"monday", n:"monday.com", cat:"prod", tier:"freemium", badge:"official", tr:"stdio",
    repo:"mondaycom/mcp", url:"https://github.com/mondaycom/mcp",
    use:"Boards, items and workflows on monday.com work OS.",
    env:["MONDAY_TOKEN"], inst:{t:"npx", v:"@mondaydotcomorg/monday-api-mcp"} },
  { id:"clickup", n:"ClickUp", cat:"prod", tier:"freemium", badge:"community", tr:"stdio",
    repo:"taazkareem/clickup-mcp-server", url:"https://github.com/taazkareem/clickup-mcp-server",
    use:"Tasks, docs, time tracking and spaces in ClickUp.",
    env:["CLICKUP_API_KEY","CLICKUP_TEAM_ID"], inst:{t:"npx", v:"@taazkareem/clickup-mcp-server@latest"} },
  { id:"todoist", n:"Todoist", cat:"prod", tier:"freemium", badge:"official", tr:"stdio",
    repo:"Doist/todoist-mcp", url:"https://github.com/Doist/todoist-mcp",
    use:"Manage Todoist tasks and projects with natural language.",
    env:["TODOIST_API_KEY"], inst:{t:"docs", v:"https://github.com/Doist/todoist-mcp"} },
  { id:"airtable", n:"Airtable", cat:"prod", tier:"freemium", badge:"community", tr:"stdio",
    repo:"domdomegg/airtable-mcp-server", url:"https://github.com/domdomegg/airtable-mcp-server",
    use:"Read/write Airtable bases, tables and records; inspect schemas.",
    env:["AIRTABLE_API_KEY"], inst:{t:"npx", v:"airtable-mcp-server"} },
  { id:"gworkspace", n:"Google Workspace", cat:"prod", tier:"free", badge:"community", tr:"stdio",
    repo:"taylorwilsdon/google_workspace_mcp", url:"https://github.com/taylorwilsdon/google_workspace_mcp",
    use:"Gmail, Drive, Calendar, Docs, Sheets, Slides — one server for all of Google.",
    env:["GOOGLE_OAUTH_CLIENT_ID","GOOGLE_OAUTH_CLIENT_SECRET"], inst:{t:"uvx", v:"workspace-mcp"},
    sec:"Community OAuth to your whole Google account — review scopes before granting." },
  { id:"ms365", n:"Microsoft 365", cat:"prod", tier:"freemium", badge:"community", tr:"stdio",
    repo:"softeria/ms-365-mcp-server", url:"https://github.com/softeria/ms-365-mcp-server",
    use:"Outlook mail, Calendar, OneDrive, Excel, Teams via Microsoft Graph.",
    env:[], inst:{t:"npx", v:"@softeria/ms-365-mcp-server"} },
  { id:"obsidian", n:"Obsidian", cat:"prod", tier:"free", badge:"community", tr:"stdio",
    repo:"MarkusPfundstein/mcp-obsidian", url:"https://github.com/MarkusPfundstein/mcp-obsidian",
    use:"Search, read and write your Obsidian vault (via Local REST API plugin).",
    env:["OBSIDIAN_API_KEY"], inst:{t:"uvx", v:"mcp-obsidian"} },
  { id:"zapier", n:"Zapier", cat:"prod", tier:"freemium", badge:"official", tr:"http",
    repo:null, url:"https://zapier.com/mcp",
    use:"Bridge to 8,000+ apps and 30,000 actions through one hosted MCP endpoint.",
    env:[], inst:{t:"docs", v:"https://zapier.com/mcp"},
    sec:"One endpoint proxies many apps — enable only the actions you actually need." },
  { id:"composio", n:"Composio", cat:"prod", tier:"freemium", badge:"official", tr:"http",
    repo:"ComposioHQ/composio", url:"https://mcp.composio.dev",
    use:"Managed auth + hosted MCPs for 500+ SaaS apps — skip OAuth plumbing.",
    env:[], inst:{t:"docs", v:"https://mcp.composio.dev"} },
  { id:"pipedream", n:"Pipedream", cat:"prod", tier:"freemium", badge:"official", tr:"http",
    repo:"PipedreamHQ/pipedream", url:"https://mcp.pipedream.com",
    use:"Hosted MCP servers for 2,500+ APIs with managed authentication.",
    env:[], inst:{t:"docs", v:"https://mcp.pipedream.com"} },

  // ---------- Communication ----------
  { id:"slack", n:"Slack", cat:"comm", tier:"free", badge:"community", tr:"stdio",
    repo:"korotovsky/slack-mcp-server", url:"https://github.com/korotovsky/slack-mcp-server",
    use:"Read channels/DMs and post messages — works even without workspace app approval.",
    env:["SLACK_MCP_XOXP_TOKEN"], inst:{t:"npx", v:"slack-mcp-server@latest"},
    sec:"Stealth token mode may violate workspace policy — prefer an approved app token." },
  { id:"discord", n:"Discord", cat:"comm", tier:"free", badge:"community", tr:"stdio",
    repo:"v-3/discordmcp", url:"https://github.com/v-3/discordmcp",
    use:"Read and send Discord messages through your bot.",
    env:["DISCORD_TOKEN"], inst:{t:"docs", v:"https://github.com/v-3/discordmcp"} },
  { id:"telegram", n:"Telegram", cat:"comm", tier:"free", badge:"community", tr:"stdio",
    repo:"chigwell/telegram-mcp", url:"https://github.com/chigwell/telegram-mcp",
    use:"Full Telegram via Telethon — read chats, send messages, manage groups.",
    env:["TG_APP_ID","TG_API_HASH"], inst:{t:"docs", v:"https://github.com/chigwell/telegram-mcp"} },
  { id:"whatsapp", n:"WhatsApp", cat:"comm", tier:"free", badge:"community", tr:"stdio",
    repo:"lharries/whatsapp-mcp", url:"https://github.com/lharries/whatsapp-mcp",
    use:"Search and send personal WhatsApp messages and media via the web multidevice API.",
    env:[], inst:{t:"docs", v:"https://github.com/lharries/whatsapp-mcp"},
    sec:"Unofficial API — account-ban risk; all message history stored locally in SQLite." },
  { id:"gmail", n:"Gmail", cat:"comm", tier:"free", badge:"community", tr:"stdio",
    repo:"GongRzhe/Gmail-MCP-Server", url:"https://github.com/GongRzhe/Gmail-MCP-Server",
    use:"Send, read, label and batch-manage Gmail with auto OAuth.",
    env:[], inst:{t:"npx", v:"@gongrzhe/server-gmail-autoauth-mcp"},
    sec:"OAuth credentials cached locally — treat ~/.gmail-mcp as a secret." },
  { id:"twilio", n:"Twilio", cat:"comm", tier:"paid", badge:"official", tr:"stdio",
    repo:"twilio-labs/mcp", url:"https://github.com/twilio-labs/mcp",
    use:"Send SMS/WhatsApp, manage numbers and calls via Twilio APIs.",
    env:["TWILIO_ACCOUNT_SID","TWILIO_API_KEY","TWILIO_API_SECRET"], inst:{t:"npx", v:"@twilio-alpha/mcp"} },
  { id:"resend", n:"Resend", cat:"comm", tier:"freemium", badge:"official", tr:"stdio",
    repo:"resend/resend-mcp", url:"https://github.com/resend/resend-mcp",
    use:"Send transactional email from the agent — plain text or HTML.",
    env:["RESEND_API_KEY"], inst:{t:"docs", v:"https://github.com/resend/resend-mcp"} },
  { id:"xquik", n:"Xquik MCP Server", cat:"search", tier:"paid", badge:"community", tr:"http",
    repo:"Xquik-dev/x-twitter-scraper", url:"https://docs.xquik.com/api-reference/overview",
    use:"Search, monitor and extract X/Twitter data; run media tools, webhooks and confirmation-gated write actions.",
    env:["XQUIK_API_KEY"], inst:{t:"http", v:"https://xquik.com/mcp"},
    sec:"Handles account data and write-capable tools — keep the API key out of prompts and review each write action." },

  // ---------- Finance & Payments ----------
  { id:"stripe", n:"Stripe", cat:"fin", tier:"freemium", badge:"official", tr:"http",
    repo:"stripe/ai", url:"https://github.com/stripe/ai",
    use:"Customers, products, payment links, invoices, refunds — plus docs search.",
    env:["STRIPE_SECRET_KEY"], inst:{t:"http", v:"https://mcp.stripe.com"},
    sec:"Use restricted API keys; test mode first — the agent can move real money." },
  { id:"paypal", n:"PayPal", cat:"fin", tier:"freemium", badge:"official", tr:"http",
    repo:null, url:"https://developer.paypal.com/tools/mcp-server/",
    use:"Invoices, orders, subscriptions and disputes on PayPal.",
    env:[], inst:{t:"http", v:"https://mcp.paypal.com/mcp"} },
  { id:"square", n:"Square", cat:"fin", tier:"freemium", badge:"official", tr:"stdio",
    repo:"square/square-mcp-server", url:"https://developer.squareup.com/docs/mcp",
    use:"Payments, catalog, customers and inventory on Square.",
    env:[], inst:{t:"docs", v:"https://developer.squareup.com/docs/mcp"} },
  { id:"plaid", n:"Plaid", cat:"fin", tier:"freemium", badge:"official", tr:"sse",
    repo:null, url:"https://plaid.com/docs/resources/mcp/",
    use:"Debug Plaid integrations — items, institutions, link tokens.",
    env:[], inst:{t:"docs", v:"https://plaid.com/docs/resources/mcp/"} },
  { id:"xero", n:"Xero", cat:"fin", tier:"paid", badge:"official", tr:"stdio",
    repo:"XeroAPI/xero-mcp-server", url:"https://github.com/XeroAPI/xero-mcp-server",
    use:"Accounting: invoices, contacts, payroll and reports in Xero.",
    env:[], inst:{t:"npx", v:"@xeroapi/xero-mcp-server@latest"} },
  { id:"coingecko", n:"CoinGecko", cat:"fin", tier:"freemium", badge:"official", tr:"stdio",
    repo:"coingecko/coingecko-typescript", url:"https://docs.coingecko.com/reference/mcp-server",
    use:"Live crypto prices, market data and coin metadata for 15k+ coins.",
    env:[], inst:{t:"docs", v:"https://docs.coingecko.com/reference/mcp-server"} },
  { id:"polygonio", n:"Massive (ex Polygon.io)", cat:"fin", tier:"freemium", badge:"official", tr:"stdio",
    repo:"massive-com/mcp_massive", url:"https://github.com/massive-com/mcp_massive",
    use:"Stocks, options, forex and crypto market data via Polygon APIs.",
    env:["POLYGON_API_KEY"], inst:{t:"docs", v:"https://github.com/massive-com/mcp_massive"} },
  { id:"findatasets", n:"Financial Datasets", cat:"fin", tier:"paid", badge:"official", tr:"stdio",
    repo:"financial-datasets/mcp-server", url:"https://github.com/financial-datasets/mcp-server",
    use:"Income statements, balance sheets and fundamentals for stock analysis.",
    env:["FINANCIAL_DATASETS_API_KEY"], inst:{t:"docs", v:"https://github.com/financial-datasets/mcp-server"} },

  // ---------- AI & ML ----------
  { id:"huggingface", n:"Hugging Face", cat:"ai", tier:"free", badge:"official", tr:"http",
    repo:null, url:"https://huggingface.co/settings/mcp",
    use:"Search models, datasets, papers and Spaces — run community tools from the Hub.",
    env:[], inst:{t:"http", v:"https://huggingface.co/mcp"} },
  { id:"elevenlabs", n:"ElevenLabs", cat:"ai", tier:"freemium", badge:"official", tr:"stdio",
    repo:"elevenlabs/elevenlabs-mcp", url:"https://github.com/elevenlabs/elevenlabs-mcp",
    use:"Text-to-speech, voice cloning, transcription and outbound voice agents.",
    env:["ELEVENLABS_API_KEY"], inst:{t:"uvx", v:"elevenlabs-mcp"} },
  { id:"replicate", n:"Replicate", cat:"ai", tier:"paid", badge:"community", tr:"stdio",
    repo:"deepfates/mcp-replicate", url:"https://github.com/deepfates/mcp-replicate",
    use:"Run any Replicate model — image gen, upscaling, video — pay per run.",
    env:["REPLICATE_API_TOKEN"], inst:{t:"docs", v:"https://github.com/deepfates/mcp-replicate"} },
  { id:"e2b", n:"E2B Code Sandbox", cat:"ai", tier:"freemium", badge:"official", tr:"stdio",
    repo:"e2b-dev/mcp-server", url:"https://github.com/e2b-dev/mcp-server",
    use:"Execute agent-written code safely in cloud sandboxes.",
    env:["E2B_API_KEY"], inst:{t:"npx", v:"@e2b/mcp-server"} },
  { id:"mem0", n:"OpenMemory (Mem0)", cat:"ai", tier:"freemium", badge:"official", tr:"stdio",
    repo:"mem0ai/mem0", url:"https://github.com/mem0ai/mem0/tree/main/openmemory",
    use:"Private, local-first shared memory across all your MCP clients.",
    env:[], inst:{t:"docs", v:"https://github.com/mem0ai/mem0/tree/main/openmemory"} },
  { id:"wandb", n:"Weights & Biases", cat:"ai", tier:"freemium", badge:"official", tr:"stdio",
    repo:"wandb/wandb-mcp-server", url:"https://github.com/wandb/wandb-mcp-server",
    use:"Query training runs, sweeps and Weave traces from your agent.",
    env:["WANDB_API_KEY"], inst:{t:"docs", v:"https://github.com/wandb/wandb-mcp-server"} },
  { id:"magic21", n:"21st.dev Magic", cat:"ai", tier:"freemium", badge:"official", tr:"stdio",
    repo:"21st-dev/magic-mcp", url:"https://github.com/21st-dev/magic-mcp",
    use:"Generate polished UI components from text — like v0 inside your IDE.",
    env:["API_KEY"], inst:{t:"npx", v:"@21st-dev/magic@latest"} },
  { id:"zenmcp", n:"Pal MCP (ex Zen)", cat:"ai", tier:"free", badge:"community", tr:"stdio",
    repo:"BeehiveInnovations/pal-mcp-server", url:"https://github.com/BeehiveInnovations/pal-mcp-server",
    use:"Multi-model orchestration — Claude consults Gemini/GPT/local models for review and debate (BYO keys).",
    env:[], inst:{t:"docs", v:"https://github.com/BeehiveInnovations/pal-mcp-server"} },

  // ---------- Security & Monitoring ----------
  { id:"sentry", n:"Sentry", cat:"secmon", tier:"freemium", badge:"official", tr:"http",
    repo:"getsentry/sentry-mcp", url:"https://github.com/getsentry/sentry-mcp",
    use:"Pull errors, issues and traces; trigger Seer root-cause analysis.",
    env:[], inst:{t:"http", v:"https://mcp.sentry.dev/mcp"} },
  { id:"grafana", n:"Grafana", cat:"secmon", tier:"free", badge:"official", tr:"stdio",
    repo:"grafana/mcp-grafana", url:"https://github.com/grafana/mcp-grafana",
    use:"Search dashboards, query Prometheus/Loki datasources, manage incidents.",
    env:["GRAFANA_URL","GRAFANA_API_KEY"], inst:{t:"docker", v:"mcp/grafana"} },
  { id:"prometheus", n:"Prometheus", cat:"secmon", tier:"free", badge:"community", tr:"stdio",
    repo:"pab1it0/prometheus-mcp-server", url:"https://github.com/pab1it0/prometheus-mcp-server",
    use:"Run PromQL, browse metrics and targets from your agent.",
    env:["PROMETHEUS_URL"], inst:{t:"docs", v:"https://github.com/pab1it0/prometheus-mcp-server"} },
  { id:"virustotal", n:"VirusTotal", cat:"secmon", tier:"freemium", badge:"community", tr:"stdio",
    repo:"w0h1v/mcp-virustotal", url:"https://github.com/w0h1v/mcp-virustotal",
    use:"Scan URLs/files/hashes and check relationships in VirusTotal.",
    env:["VIRUSTOTAL_API_KEY"], inst:{t:"npx", v:"@burtthecoder/mcp-virustotal"} },
  { id:"shodan", n:"Shodan", cat:"secmon", tier:"paid", badge:"community", tr:"stdio",
    repo:"w0h1v/mcp-shodan", url:"https://github.com/w0h1v/mcp-shodan",
    use:"Query internet-exposed hosts, DNS and CVE data for recon (authorized use).",
    env:["SHODAN_API_KEY"], inst:{t:"npx", v:"@burtthecoder/mcp-shodan"} },
  { id:"ghidra", n:"Ghidra", cat:"secmon", tier:"free", badge:"community", tr:"stdio",
    repo:"LaurieWired/GhidraMCP", url:"https://github.com/LaurieWired/GhidraMCP",
    use:"LLM-assisted reverse engineering — decompile, rename, annotate binaries in Ghidra.",
    env:[], inst:{t:"docs", v:"https://github.com/LaurieWired/GhidraMCP"} },
  { id:"burp", n:"Burp Suite", cat:"secmon", tier:"freemium", badge:"official", tr:"stdio",
    repo:"PortSwigger/mcp-server", url:"https://github.com/PortSwigger/mcp-server",
    use:"Drive Burp's proxy history, Repeater and scanner from an AI client (authorized testing).",
    env:[], inst:{t:"docs", v:"https://github.com/PortSwigger/mcp-server"} },

  // ---------- Design & 3D ----------
  { id:"figma", n:"Figma Dev Mode", cat:"design", tier:"paid", badge:"official", tr:"http",
    repo:null, url:"https://help.figma.com/hc/en-us/articles/32132100833559",
    use:"Design-to-code with real variables, components and layout data (needs Dev/Full seat).",
    env:[], inst:{t:"http", v:"http://127.0.0.1:3845/mcp"} },
  { id:"framelink", n:"Framelink (Figma)", cat:"design", tier:"free", badge:"community", tr:"stdio",
    repo:"GLips/Figma-Context-MCP", url:"https://github.com/GLips/Figma-Context-MCP",
    use:"Free Figma-to-code alternative — pulls simplified design data via API token.",
    env:["FIGMA_API_KEY"], inst:{t:"npx", v:"figma-developer-mcp", args:["--stdio"]} },
  { id:"canva", n:"Canva", cat:"design", tier:"freemium", badge:"official", tr:"stdio",
    repo:null, url:"https://www.canva.dev/docs/apps/mcp-server/",
    use:"Generate, autofill and export Canva designs from your agent.",
    env:[], inst:{t:"docs", v:"https://www.canva.dev/docs/apps/mcp-server/"} },
  { id:"blender", n:"Blender", cat:"design", tier:"free", badge:"community", tr:"stdio",
    repo:"ahujasid/blender-mcp", url:"https://github.com/ahujasid/blender-mcp",
    use:"Prompt-driven 3D — create scenes, materials and models in Blender.",
    env:[], inst:{t:"uvx", v:"blender-mcp"} },
  { id:"unity", n:"Unity", cat:"design", tier:"free", badge:"community", tr:"stdio",
    repo:"CoplayDev/unity-mcp", url:"https://github.com/CoplayDev/unity-mcp",
    use:"Manage Unity scenes, scripts and assets with an AI copilot.",
    env:[], inst:{t:"docs", v:"https://github.com/CoplayDev/unity-mcp"} },
  { id:"godot", n:"Godot", cat:"design", tier:"free", badge:"community", tr:"stdio",
    repo:"Coding-Solo/godot-mcp", url:"https://github.com/Coding-Solo/godot-mcp",
    use:"Launch the editor, run projects and debug scenes in Godot.",
    env:[], inst:{t:"docs", v:"https://github.com/Coding-Solo/godot-mcp"} },

  // ---------- Knowledge & Content ----------
  { id:"wikipedia", n:"Wikipedia", cat:"know", tier:"free", badge:"community", tr:"stdio",
    repo:"Rudra-ravi/wikipedia-mcp", url:"https://github.com/Rudra-ravi/wikipedia-mcp",
    use:"Search and summarize Wikipedia — grounded factual context, no key needed.",
    env:[], inst:{t:"uvx", v:"wikipedia-mcp"} },
  { id:"arxiv", n:"arXiv", cat:"know", tier:"free", badge:"community", tr:"stdio",
    repo:"blazickjp/arxiv-mcp-server", url:"https://github.com/blazickjp/arxiv-mcp-server",
    use:"Search, download and analyze research papers from arXiv.",
    env:[], inst:{t:"uvx", v:"arxiv-mcp-server"} },
  { id:"youtube", n:"YouTube Transcript", cat:"know", tier:"free", badge:"community", tr:"stdio",
    repo:"jkawamoto/mcp-youtube-transcript", url:"https://github.com/jkawamoto/mcp-youtube-transcript",
    use:"Pull video transcripts for summarizing talks and tutorials.",
    env:[], inst:{t:"uvx", v:"mcp-youtube-transcript"} },
  { id:"excel", n:"Excel", cat:"know", tier:"free", badge:"community", tr:"stdio",
    repo:"haris-musa/excel-mcp-server", url:"https://github.com/haris-musa/excel-mcp-server",
    use:"Create and edit .xlsx — formulas, charts, pivots — without Excel installed.",
    env:[], inst:{t:"uvx", v:"excel-mcp-server", args:["stdio"]} },
  { id:"pandoc", n:"Pandoc", cat:"know", tier:"free", badge:"community", tr:"stdio",
    repo:"vivekVells/mcp-pandoc", url:"https://github.com/vivekVells/mcp-pandoc",
    use:"Convert documents between markdown, docx, PDF, HTML, epub.",
    env:[], inst:{t:"uvx", v:"mcp-pandoc"} },
  { id:"markdownify", n:"Markdownify", cat:"know", tier:"free", badge:"community", tr:"stdio",
    repo:"zcaceres/markdownify-mcp", url:"https://github.com/zcaceres/markdownify-mcp",
    use:"Convert PDFs, images, audio and web pages to markdown.",
    env:[], inst:{t:"docs", v:"https://github.com/zcaceres/markdownify-mcp"} },
  { id:"spotify", n:"Spotify", cat:"know", tier:"freemium", badge:"community", tr:"stdio",
    repo:"varunneal/spotify-mcp", url:"https://github.com/varunneal/spotify-mcp",
    use:"Search and control Spotify playback, manage playlists (playback needs Premium).",
    env:["SPOTIFY_CLIENT_ID","SPOTIFY_CLIENT_SECRET"], inst:{t:"docs", v:"https://github.com/varunneal/spotify-mcp"} },
  { id:"homeassistant", n:"Home Assistant", cat:"know", tier:"free", badge:"official", tr:"sse",
    repo:"home-assistant/core", url:"https://www.home-assistant.io/integrations/mcp_server/",
    use:"Control lights, sensors and automations in your smart home.",
    env:[], inst:{t:"docs", v:"https://www.home-assistant.io/integrations/mcp_server/"} },

  // ---------- Business & CRM ----------
  { id:"shopify", n:"Shopify Dev", cat:"biz", tier:"freemium", badge:"official", tr:"stdio",
    repo:null, url:"https://shopify.dev/docs/apps/build/devmcp",
    use:"Search Shopify docs and explore Admin GraphQL schema while building apps.",
    env:[], inst:{t:"npx", v:"@shopify/dev-mcp@latest"} },
  { id:"hubspot", n:"HubSpot", cat:"biz", tier:"freemium", badge:"official", tr:"stdio",
    repo:null, url:"https://developers.hubspot.com/mcp",
    use:"CRM contacts, companies, deals and tickets from your agent.",
    env:["PRIVATE_APP_ACCESS_TOKEN"], inst:{t:"docs", v:"https://developers.hubspot.com/mcp"} },
  { id:"llmpulse", n:"LLM Pulse", cat:"biz", tier:"paid", badge:"official", tr:"http",
    repo:"LLM-Pulse/llmpulse-mcp", url:"https://github.com/LLM-Pulse/llmpulse-mcp",
    use:"AI search visibility analytics: brand mentions, citations, sentiment, share of voice, recommendations and AI traffic.",
    env:["LLMPULSE_API_KEY"], inst:{t:"http", v:"https://api.llmpulse.ai/api/v1/mcp"},
    sec:"Use project-scoped API keys; write tools can create prompts, tags, annotations and GEO Writer tasks." },
  { id:"intercom", n:"Intercom", cat:"biz", tier:"paid", badge:"official", tr:"http",
    repo:null, url:"https://developers.intercom.com/docs/guides/mcp",
    use:"Search conversations, tickets and customer data in Intercom.",
    env:[], inst:{t:"http", v:"https://mcp.intercom.com/mcp"} },
  { id:"kafka", n:"Confluent (Kafka)", cat:"biz", tier:"freemium", badge:"official", tr:"stdio",
    repo:"confluentinc/mcp-confluent", url:"https://github.com/confluentinc/mcp-confluent",
    use:"Manage Kafka topics, connectors and Flink SQL on Confluent Cloud.",
    env:[], inst:{t:"docs", v:"https://github.com/confluentinc/mcp-confluent"} },
  { id:"notfair", n:"NotFair", cat:"biz", tier:"freemium", badge:"community", tr:"stdio",
    repo:"nowork-studio/NotFair", url:"https://github.com/nowork-studio/NotFair",
    use:"Open-source Claude Code skills for SEO, GEO/AEO and paid ads that bundle four MCP servers — Google Search Console, Google Analytics (GA4), Google Ads and Meta Ads — for live account data.",
    env:["GOOGLE_ADS_CREDENTIALS","META_ADS_CREDENTIALS","GSC_CREDENTIALS","GA4_CREDENTIALS"], inst:{t:"docs", v:"https://github.com/nowork-studio/NotFair"},
    sec:"Connects to Google and Meta ad/analytics accounts via OAuth — scope credentials to only the accounts you want the agent to touch." }
  { id:"agentservices", n:"AgentServices", cat:"fin", tier:"paid", badge:"community", tr:"http",
    repo:"vbkotecha/aiservices-api", url:"https://agentservices.to",
    use:"54-service paid data API for AI agents — crypto prices, forex, stocks, news, IP geo, DeFi yields with x402 micropayments.",
    env:[], inst:{t:"http", v:"https://agentservices.to/mcp"} },
];
