// Regenerates stars.js from GitHub API. Usage: GITHUB_TOKEN=... node fetch-stars.mjs
import { readFileSync, writeFileSync } from "fs";

const data = readFileSync(new URL("./data.js", import.meta.url), "utf8");
const repos = [...new Set([...data.matchAll(/repo:\s*"([^"]+)"/g)].map(m => m[1]))];
const token = process.env.GITHUB_TOKEN;
const stars = {}, missing = [];

for (const repo of repos) {
  const res = await fetch(`https://api.github.com/repos/${repo}`, {
    headers: { "User-Agent": "mcp-directory", ...(token ? { Authorization: `Bearer ${token}` } : {}) }
  });
  if (res.status === 200) {
    const j = await res.json();
    stars[repo] = j.stargazers_count;
    if (j.full_name.toLowerCase() !== repo.toLowerCase()) console.log(`MOVED: ${repo} -> ${j.full_name}`);
  } else {
    missing.push(`${res.status} ${repo}`);
  }
  await new Promise(r => setTimeout(r, 120));
}

writeFileSync(new URL("./stars.js", import.meta.url),
  "// GitHub star counts baked at build time — regenerated by fetch-stars.mjs\nconst STARS = " +
  JSON.stringify(stars, null, 0) + ";\n");

console.log(`OK ${Object.keys(stars).length}/${repos.length} repos`);
if (missing.length) { console.log("MISSING:"); missing.forEach(m => console.log("  " + m)); }
